version: "3.9"
services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    ports:
      - 8000-8003:8000
    volumes:
      - .:/src
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db