# Generated by Django 4.0.4 on 2022-05-15 17:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('unique_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('total_questions', models.PositiveIntegerField()),
                ('total_steps', models.PositiveIntegerField()),
                ('show_result_immediately', models.BooleanField(default=True)),
                ('is_time_bound', models.BooleanField(default=True)),
                ('time_in_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('start_together', models.BooleanField(default=False)),
                ('submit_one_by_one', models.BooleanField(default=False)),
                ('time_per_quiz_in_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.hostuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('answers', models.TextField()),
                ('time_taken_in_minutes', models.PositiveIntegerField()),
                ('participant_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quizapp.quizsession')),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submissions', to='quizapp.quizsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('step_title', models.CharField(max_length=50)),
                ('step_description', models.TextField(blank=True, null=True)),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quizsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=1024)),
                ('options_count', models.PositiveIntegerField(default=4)),
                ('has_multiple_answers', models.BooleanField(default=False)),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quizsession')),
                ('quiz_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizapp.quizstep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('position', models.CharField(max_length=1)),
                ('answer', models.CharField(max_length=500)),
                ('is_right_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
