# Generated by Django 4.0.4 on 2022-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='allow_multiple_submission',
            field=models.BooleanField(default=False),
        ),
    ]
