# Generated by Django 4.0.4 on 2022-07-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_submission_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='title',
            field=models.CharField(default='hello world', max_length=200),
            preserve_default=False,
        ),
    ]
