# Generated by Django 4.0.6 on 2022-07-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_quizsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
